export default {
	useTabs: true,
	printWidth: 120,
	plugins: ["prettier-plugin-packagejson", "@ianvs/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
	importOrder: [
		"<TYPES>",
		"<TYPES>^[.]",
		"",
		"<BUILTIN_MODULES>",
		"",
		"^react$",
		"^react-dom$",
		"",
		"<THIRD_PARTY_MODULES>",
		"",
		"^(?!.*[.]css$)[./].*$",
		".css$",
	],
	importOrderCaseSensitive: true,
	importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
	importOrderTypeScriptVersion: "5.0.0",
	tailwindConfig: "./tailwind.config.js",
	tailwindFunctions: ["cx", "clsx", "twMerge"],
};
